### ISSUE TITLE
Link to Magicka Mastery

### ISSUE THREAD

**Issue by feanarosurion** [rfuzzo/MorrowindPlusPlus#1]
The link to Magicka Mastery MWSE doesn't work. I found the file in assets but it doesn't work in the guide.

**Comment by rfuzzo** [comment]
Thank you! Fixed it now, it was locally hosted in this github repo: https://github.com/rfuzzo/MorrowindPlusPlus/blob/main/assets/magickaMastery.zip

**Comment by feanarosurion** [comment]
Hi, great, glad I could help!

One issue, the new archive doesn't have a folder structure or include any
instructions how to install (or a Readme). That would be helpful here too.

**Comment by rfuzzo** [comment]
ah right, yeah good point! I'll change the archive structure soon
