### ISSUE TITLE
A mix-up in Landscape (Add-ons) section. (Questions as well.)

### ISSUE THREAD

**Issue by Wvlfe** [rfuzzo/MorrowindPlusPlus#6]
In the Landscape Add-ons section.

The link for Investigations at Tel Eurus mod sends you to the Memento Mori mod.
I thought I was going crazy for a moment before realizing.
Will provide a link here so you don't have to go find it.

(Happy New Years by the way! 🥂🎉🎆) 

https://www.nexusmods.com/morrowind/mods/51938

**Comment by rfuzzo** [comment]
Thank you! And happy new year too!

**Comment by Wvlfe** [comment]
Hey again rfuzzo.
A question about one of the steps in the finish section. 
Would any of the mods that have BCOM in them inside of Mash64 also count towards this as well as did you mean Patch For Purists?

![firefox_TaHhYn52SJ](https://user-images.githubusercontent.com/121589844/210193953-7ff998a0-d805-4299-ae85-c503b9f0b1fd.png)

**Comment by Wvlfe** [comment]
Finally finished with the install but the game came up with this error. 
![Morrowind_zoM0hcvGHg](https://user-images.githubusercontent.com/121589844/210200695-166c0425-aa4e-42e1-90c3-32e2f0731c91.png)

**Comment by Wvlfe** [comment]
As well as I'm not sure if the game is supposed to be coming up with warnings. 
I really do hope I didn't mess up anything crucial. 😵‍

**Comment by Wvlfe** [comment]
Alright, so apparently Abot's mods are broken with TR.
R-Zero pointed that out to me as well as from comments in TR's discord.

I will come back with the result after disabling Abot's mods.

**Comment by rfuzzo** [comment]
Yeah I'll remove abots travel mods, thanks for reminding me

**Comment by Wvlfe** [comment]
Shame but it's apparently he's quite upset from TR breaking his mods with updates.
So he's opted not to update his, so unsure if he will.

**Comment by Wvlfe** [comment]
Hey fuzzo, I looked at his mods on nexus and he's provided two ways of using his mods for the 3 travel mods.

**BOATS**
2. IF you are using Tamriel Rebuilt version 22.11 or higher, probably simpler way to update and keep using the mod in Vvardenfell routes is:
a) remove from your loading list abotBoatsTR2101.esp and abotRiverStridersTR2101.esp, run the game and load a save ignoring error messages, make a new save (e.g. called boatsupdate)
b) add abotBoats.esp to your loading list, run the game, load the boatsupdate save, make a new save and eventually use Wrye Mash\repair all on it

3. ELSE IF like me you keep using TR Version 21.01/TR_Preview.esp, don't load abotBoats.esp, load in this (relative) order:
TR_Preview.esp
TR_Travels_(Preview_and_Mainland).esp
abotBoatsTR2101.esp
abotRiverStridersTR2101.esp

**GONDOLIERS**

2.IF YOU ARE USING latest Tamriel Rebuilt 22.11:
By default Gondoliers mod enables 2 new gondoliers and a Tel Mora <--> Firewatch route AFTER the blight is gone/main game quest has been completed.
As latest 22.11 version of Tamriel Rebuilt completely changed Firewatch, if you are using it you may want to disable the route from the mod in-game configuration menu, setting "Enable trips to mainland" option to "No" .
Alternatively you can do it directly using
set ab01goNoMainland to 2
from the in game console

**SILT STRIDERS**
2. IF you are using Tamriel Rebuilt version 22.11 or higher, probably simpler way to update and keep using the mod in Vvardenfell routes is:
a) remove from your loading list abotSiltStridersTR2101.esp, run the game and load a save ignoring error messages, make a new save (e.g. called striderssupdate)
b) add abotSiltStriders.esp to your loading list, run the game, load the stridersupdate save, make a new save and eventually use Wrye Mash\repair all on it

3. ELSE IF like me you keep using TR Version 21.01/TR_Preview.esp, don't load abotSiltStriders.esp, load in this (relative) order:
TR_Preview.esp
TR_Travels_(Preview_and_Mainland).esp
abotSiltStridersTR2101.esp

**Comment by Wvlfe** [comment]
Game is running okay but everyone I speak to opens up just like this. 
As well as most of my warnings in the text file have

> Script variable "PC_NoLore" not found for dialogue type Topic
Info "EMPTY"

![image](https://user-images.githubusercontent.com/121589844/210272596-6d24b422-7734-48cf-9eb3-f1a0b665aa0d.png)

**Comment by rfuzzo** [comment]
Did you merge the mods with tes3merge?

And about boats/gondoliers/striders: I think I'll actually remove them for my own modded game too - the travelling is quite choppy and jarring and so unimmersive that I actually never use it in-game...

I might add a section on "suggestions/honorable mentions" to the guide and move some mods there...

**Comment by Wvlfe** [comment]
Well, I've ran tes3merge but no ESP specifically named Merged Objects.ESP comes up. 
Except these two but let me try to see if that'll work.
![ModOrganizer_zZkKRHP6HR](https://user-images.githubusercontent.com/121589844/210274561-2d5ba4ca-fc6a-422a-af74-3b134decf4aa.png)
